### ISSUE TITLE
Issue with the Length of Category Label

### ISSUE THREAD

**Issue by annnvv** [janbrogger/putdocxfreqtable#1]
Is there a limit on how long the category labels can be to be output in a table using putdocxfreqtable? If there is, would you be able to increase the limit?

I am encountering an error with a value label being too long (invalid name r(198);). The reason I believe this is the issue is because if I shorten the label to 32 characters or fewer, I don't encounter this issue.

**Comment by janbrogger** [comment]
Fixed.
