### ISSUE TITLE
PUTDOCX FREQ TABLE and Setup the Number of Decimals

### ISSUE THREAD

**Issue by roywongcr** [janbrogger/putdocxfreqtable#3]
Hi, I am currently using the PUTDOCXFREQTABLE in Stata 15.1 which is an excellent contribution, many thanks for that.

I have a question: I get from Stata results in a percentage estimation with several decimals but in the .docx file generated the decimals aren't present. How I could solve it?

Many thanks, Roy

**Comment by janbrogger** [comment]
Fixed. Download the new code from GitHub here. I've sent the new version to Kit Baum at SSC so you should within a few days be able to do "ssc install putdocxfreqtable".

**Comment by roywongcr** [comment]
Dear Jan

Many thanks for your response and support. 

Best regards, Roy
